import { useLocation } from "wouter";
import Footer from "@/components/Footer";
import { ArrowLeft } from "lucide-react";

export default function Terms() {
  const [, navigate] = useLocation();
  const effectiveDate = "March 23, 2026";

  return (
    <div className="min-h-screen bg-background">
      <div className="border-b border-border bg-white px-6 py-4 flex items-center gap-4 sticky top-0 z-10">
        <button onClick={() => navigate("/")} className="text-muted-foreground hover:text-foreground transition-colors">
          <ArrowLeft className="w-5 h-5" />
        </button>
        <h1 className="font-semibold text-foreground">Terms of Service</h1>
      </div>

      <div className="max-w-3xl mx-auto px-4 py-10 prose prose-slate">
        <h1 className="text-2xl font-bold text-foreground mb-2">Terms of Service</h1>
        <p className="text-muted-foreground text-sm mb-8">Effective date: {effectiveDate}</p>

        <div className="space-y-6 text-foreground text-sm leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold mb-2">1. Acceptance of Terms</h2>
            <p>By accessing or using ProposAI ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">2. Description of Service</h2>
            <p>ProposAI is a software-as-a-service (SaaS) platform that enables trade contractors — including HVAC technicians, plumbers, electricians, and roofers — to generate professional job proposals using artificial intelligence. The Service includes AI-powered proposal generation, PDF export, email delivery, and proposal tracking features.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">3. Subscription Plans and Billing</h2>
            <p>The Service is offered under three plans: Free (3 proposals per month at no charge), Starter ($29.00 USD per month, 20 proposals), and Pro ($59.00 USD per month, unlimited proposals). Paid subscriptions are billed monthly in advance. You may cancel your subscription at any time through the billing portal; cancellation takes effect at the end of the current billing period.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">4. Refund Policy</h2>
            <p>We offer a 7-day money-back guarantee on your first payment for any paid plan. If you are not satisfied within 7 days of your first charge, contact us at support@proposai.org for a full refund. After 7 days, subscription fees are non-refundable except where required by applicable law.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">5. Acceptable Use</h2>
            <p>You agree to use the Service only for lawful purposes. You must not use the Service to generate fraudulent proposals, misrepresent your identity or business, transmit spam or unsolicited communications, or violate any applicable laws or regulations.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">6. AI-Generated Content</h2>
            <p>Proposals generated by the Service are produced by artificial intelligence and are provided as a starting point. You are solely responsible for reviewing, editing, and verifying all AI-generated content before sending it to clients. ProposAI makes no warranty that generated proposals are accurate, complete, or suitable for any specific job or jurisdiction.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">7. Intellectual Property</h2>
            <p>You retain ownership of all content you input into the Service and all proposals you generate. By using the Service, you grant ProposAI a limited license to process your inputs solely for the purpose of providing the Service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">8. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, ProposAI shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service. Our total liability to you for any claim shall not exceed the amount you paid us in the 12 months preceding the claim.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">9. Termination</h2>
            <p>We reserve the right to suspend or terminate your account at any time if you violate these Terms. You may delete your account at any time by contacting support@proposai.org.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">10. Changes to Terms</h2>
            <p>We may update these Terms from time to time. We will notify you of material changes by email or by posting a notice on the Service. Continued use of the Service after changes take effect constitutes acceptance of the updated Terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">11. Contact</h2>
            <p>For questions about these Terms, contact us at: <a href="mailto:support@proposai.org" className="text-primary underline">support@proposai.org</a></p>
          </section>
        </div>
      </div>
    <Footer />
    </div>
  );
}
